language: node_js
dist: xenial
node_js:
  - "10"
  - "11"
before_script: .travis/before_script.sh
script: .travis/script.sh
jobs:
  include:
    - stage: deploy
      node_js: "11"
      script: .travis/deploy.sh

stages:
  - test
  - name: deploy
    if: branch = master